export const actions = {
    readAll: 'read_all',
    readSome: 'read_some',
    readSelf: 'read_self',
    read: 'read',
    create: 'create',
    update: 'update',
    delete: 'delete'
};

export const features = {
    user: 'User',
    attendance: 'Attendance',
    expense: 'Expense',
    leave: 'Leave',
    department: 'Department',
    designation: 'Designation',
    report: 'Report',
    setting: 'Setting',
    calendar: 'Calendar',
    configuration: 'Configuration',
    approve: "Approve",
    leavereport: 'Leave Report',
    overview: 'Overview',
    timerequest: 'Time Request',
    taskrequest: 'Task Request',
    workschedule: 'Work Schedule',
    projects: 'Projects',
    projectlist: 'Project List',
    projectoverview: "Project Overview",
    projecttimesheet: "Project Timesheet",
    client: "Client",
    tasks:"My Tasks",
    projectsemployee: "Projects",
    tasknote: "Task Note",
    timeline: "Timeline",
    usertimeline: "Timeline",
    userleave:'Leave',
};